create_clock -period 10.000 -name i_clock -waveform {0.000 5.000} [get_ports i_clock]

set_property MARK_DEBUG true [get_nets {data_in[5]}]
set_property MARK_DEBUG true [get_nets {data_out[1]}]
set_property MARK_DEBUG true [get_nets {data_out[5]}]
set_property MARK_DEBUG true [get_nets {data_out[7]}]
set_property MARK_DEBUG true [get_nets spi_mosi]
set_property MARK_DEBUG true [get_nets {data_in[4]}]
set_property MARK_DEBUG true [get_nets {data_in[0]}]
set_property MARK_DEBUG true [get_nets done]
set_property MARK_DEBUG true [get_nets {data_in[1]}]
set_property MARK_DEBUG true [get_nets {data_out[0]}]
set_property MARK_DEBUG true [get_nets {data_out[2]}]
set_property MARK_DEBUG true [get_nets spi_cs_n]
set_property MARK_DEBUG true [get_nets {data_out[6]}]
set_property MARK_DEBUG true [get_nets {spi_clock_divider[1]}]
set_property MARK_DEBUG true [get_nets {spi_clock_divider[2]}]
set_property MARK_DEBUG true [get_nets {spi_clock_divider[3]}]
set_property MARK_DEBUG true [get_nets {data_in[2]}]
set_property MARK_DEBUG true [get_nets {data_in[6]}]
set_property MARK_DEBUG true [get_nets {data_out[3]}]
set_property MARK_DEBUG true [get_nets {spi_clock_divider[0]}]
set_property MARK_DEBUG true [get_nets {spi_clock_divider[4]}]
set_property MARK_DEBUG true [get_nets clock_phase]
set_property MARK_DEBUG true [get_nets spi_clock]
set_property MARK_DEBUG true [get_nets spi_miso]
set_property MARK_DEBUG true [get_nets {data_in[3]}]
set_property MARK_DEBUG true [get_nets {data_in[7]}]
set_property MARK_DEBUG true [get_nets {data_out[4]}]
set_property MARK_DEBUG true [get_nets clock_polarity]
set_property MARK_DEBUG true [get_nets enable]
set_property MARK_DEBUG true [get_nets busy]


set_property MARK_DEBUG false [get_nets i_clock_IBUF_BUFG]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list i_clock_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {data_out[0]} {data_out[1]} {data_out[2]} {data_out[3]} {data_out[4]} {data_out[5]} {data_out[6]} {data_out[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {data_in[0]} {data_in[1]} {data_in[2]} {data_in[3]} {data_in[4]} {data_in[5]} {data_in[6]} {data_in[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 5 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {spi_clock_divider[0]} {spi_clock_divider[1]} {spi_clock_divider[2]} {spi_clock_divider[3]} {spi_clock_divider[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list busy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list clock_phase]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list clock_polarity]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list done]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list spi_clock]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list spi_cs_n]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list spi_miso]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list spi_mosi]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets i_clock_IBUF_BUFG]
